### ISSUE TITLE
Consider dropping `Hetzner` prefix

### ISSUE THREAD

**Issue by sschwarzer** [lsymds/hetznercloud-py#1]
Many if not all classes have a `Hetzner` prefix, for example `hetznercloud.exceptions.HetznerAuthenticationException` or `hetznercloud.client.HetznerCloudClientConfiguration`.

I think that's unnecessarily verbose. The package name `hetznercloud` already makes it sufficiently clear that this is the API for a Hetzner product. :-)

**Comment by sschwarzer** [comment]
I would provide a pull request if you're interested.

**Comment by ghost** [comment]
Hmm.. the reason I initially had it like that was to provide clarity when the classes are imported, for example:

```
from hetznercloud import HetznerCloudClient
x = HetznerCloudClient()
```

is a lot more verbose and potentially open to less conflicts than naming it 'CloudClient' or just 'Client'.

**Comment by sschwarzer** [comment]
I also think `Client` may be a bit too unspecific. But I'd rather drop the `Hetzer` prefix than keep it. :-) To me it just feels so extremely redundant.

**Comment by ghost** [comment]
No problem. I tell you what, I'll get the rest of the API finished in develop mode and will then remove it from everywhere but the two entry points into the API (HetznerCloudClient and HetznerCloudConfiguration). The exceptions are so unlikely to conflict with anything else that they needn't have the prefix.

**Comment by sschwarzer** [comment]
Great! :-)

**Comment by ghost** [comment]
For now, I've actually decided to leave them in. I will field responses from others and decide whether or not they should be removed.
