### ISSUE TITLE
SERVER_TYPE_8CPU_32GB should be "cx51"

### ISSUE THREAD

**Issue by ifor** [lsymds/hetznercloud-py#15]
Currently in constants.py, 

SERVER_TYPE_8CPU_32GB = "cx41"
SERVER_TYPE_8CPU_32GB_CEPH = "cx41-ceph"

.. should be "cx51" ??

**Comment by ghost** [comment]
Good eye. I'll fix this now.

**Comment by ghost** [comment]
Hey @ifor, this has been pushed to the package repository.
