### ISSUE TITLE
FloatingIp field `ip` not parsed from api json

### ISSUE THREAD

**Issue by svensp** [lsymds/hetznercloud-py#19]
I'm trying to identify an floating ip in the api by the ip address it represents. Unless I'm reading it wrong HetznerCloudFloatingIp._load_from_json does not parse that information yet.

I think the following would parse that information:
```python
float_ip.ip = json["ip"]
```

**Comment by ghost** [comment]
Feel free to submit a pull request if you need it done as soon as possible, otherwise I will do it this weekend.

Thanks for the report!
