### ISSUE TITLE
Image deletion raises exception

### ISSUE THREAD

**Issue by BRoehrl** [lsymds/hetznercloud-py#28]
When an image is deleted with image.delete(), a HetznerActionException is raised even though the image is successfully deleted.
This is because the returned HTTP status from the API is 204 No Content.
But the program only accepts status_code 200.

See:
images.py line 69

**Comment by thlisym** [comment]
Thanks for the report. This has been fixed and will be released in the next version.

**Comment by lsymds** [comment]
Hi! You should look into using the official HCloud Python library as this one is deprecated (and has been for a while now).

https://github.com/hetznercloud/hcloud-python
