### ISSUE TITLE
Volume support

### ISSUE THREAD

**Issue by svensp** [lsymds/hetznercloud-py#32]
Hetzner has launched its cloud volume feature.

As before with the floating ip I'd like to implement a pacemaker resource agent using your library to manage volumes with pacemaker. Are there plans to implement the new api yet?

**Comment by franzs** [comment]
I added initial support for volumes:

https://github.com/franzs/hetznercloud-py/tree/volume-support

It certainly needs some polish. And a documentation is missing. But you can take a look at it if you like.

**Comment by franzs** [comment]
A documentation for volumes is available at:

https://github.com/franzs/hetznercloud-py/blob/volume-support/README.md#volumes

**Comment by franzs** [comment]
Finally I opened a PR #33.

**Comment by lsymds** [comment]
Hi! You should look into using the official HCloud Python library as this one is deprecated (and has been for a while now).

https://github.com/hetznercloud/hcloud-python
